/**
 * @file Led.c
 * @author Seb Madgwick
 * @brief LED driver.
 */

//------------------------------------------------------------------------------
// Includes

#include "definitions.h"
#include "Led.h"
#include "PeripheralBusClockFrequency.h"
#include <stdint.h>

//------------------------------------------------------------------------------
// Variables

static const uint16_t normal = 0x1FFF;
static const uint16_t bright = 0xFFFF;

//------------------------------------------------------------------------------
// Functions

/**
 * @brief Initialises the module.  This function must only be called once, on
 * system startup.
 */
void LedInitialise(void) {

    // Configure PWM
    CCP3CON1bits.MOD = 0b0100; // Dual Edge Compare mode
    CCP3CON1bits.ON = 1;

    // Configure state update timer
    CCP2CON1bits.T32 = 1;
    CCP2PR = PERIPHERAL_BUS_CLOCK_FREQUENCY / 5; // 5 Hz
    CCP2CON1bits.ON = 1;
    EVIC_SourceStatusClear(INT_SOURCE_CCT2);
    EVIC_SourceEnable(INT_SOURCE_CCT2);
}

/**
 * @brief CCT interrupt handler.  This function should be called by the ISR
 * implementation generated by MPLAB Harmony.
 */
void Cct2InterruptHandler(void) {
    if (CCP3RB == normal) {
        CCP3RB = bright;
    } else {
        CCP3RB = normal;
    }
    EVIC_SourceStatusClear(INT_SOURCE_CCT2);
}

/**
 * @brief Set LED mode.
 * @param mode Mode.
 */
void LedSet(const LedMode mode) {
    switch (mode) {
        case LedModeNormal:
            EVIC_SourceDisable(INT_SOURCE_CCT2);
            CCP3RB = normal;
            break;
        case LedModeBright:
            EVIC_SourceDisable(INT_SOURCE_CCT2);
            CCP3RB = bright;
            break;
        case LedModeFlashing:
            EVIC_SourceEnable(INT_SOURCE_CCT2);
            break;
    }
}

//------------------------------------------------------------------------------
// End of file
